# Generated by Django 3.1.8 on 2022-12-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNP', models.CharField(max_length=13, verbose_name='Cod numeric personal')),
                ('name', models.CharField(max_length=100, verbose_name='Nume')),
                ('gender', models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Gen')),
                ('age', models.IntegerField(verbose_name='Varsta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
