# Generated by Django 3.1.8 on 2022-12-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.EmailField(default='introdu email', max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='CNP',
            field=models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='Cod numeric personal'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female')], max_length=10, verbose_name='Gen'),
        ),
    ]
