# Generated by Django 3.1.8 on 2022-12-11 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0003_person_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-name'], 'verbose_name_plural': 'People'},
        ),
        migrations.AddField(
            model_name='person',
            name='detaliiMedicale',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('adeverinta', 'Adeverinta'), ('reteta', 'reteta'), ('trimitere', 'trimitere'), ('altceva', 'altceva')], max_length=20, verbose_name='Tip')),
                ('details', models.CharField(max_length=1000, verbose_name='Detalii')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pf.person')),
            ],
            options={
                'verbose_name_plural': 'Requests',
                'ordering': ['-type'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(max_length=1000, verbose_name='Detalii')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pf.request')),
            ],
            options={
                'verbose_name_plural': 'Documents',
                'ordering': ['-request'],
            },
        ),
    ]
