# Generated by Django 4.1.4 on 2022-12-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pf', '0004_auto_20221211_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='type',
            field=models.CharField(choices=[('adeverinta', 'Adeverinta'), ('reteta', 'Reteta'), ('trimitere', 'Trimitere'), ('altceva', 'Altceva')], max_length=20, verbose_name='Tip'),
        ),
    ]
